- hosts: localhost
  #become: yes
  tasks:
    - name: Install jq 
      yum:
        name: jq
        state: present
        
    - name: validation 
      debug: 
        msg: "{{item}} is installed"
      when: '"{{item}}" in ansible_facts.packages'
      with_items:
        - jq

