- hosts: localhost
  #become: yes
  tasks:
    - name: Install jq 
      yum:
        name: jq
        state: present
        
    - name: validation 
      package:
        name: jq
        state: present
      check_mode: true
      register: package_check

    - name: print results
      debug:
        msg: "jq package is installed"
      when: package_check is succeeded

